theme: jekyll-theme-cayman
title: 2020年北京理工大学强制将毕业生宿舍行李物品寄走事件
subtitle: https://flyerwg.github.io/bit_move_dorm/
description: https://flyerwg.github.io/bit_move_dorm/
keywords: 北京理工大学,毕业生,北京高校,行李
author: flyerwg
language: zh-CN
